# Documentation
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

os: linux

sudo: required

language: node_js
node_js:
  - "10"

cache:
  - npm
  - yarn
  - truffle

before_install:
  - npm install -g yarn
  - npm install -g node-gyp

before_script:
  - cd truffle-project

script:
  - npm install
  - yarn gen:loom-key
  - yarn loom:init > /dev/null 2>&1 &
  - yarn loom:run &
  - sleep 5
  - yarn deploy
  - yarn serve > /dev/null 2>&1 &
