# Documentation
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

os: linux

sudo: required

language: node_js
node_js:
  - "10"

cache:
  - npm
  - yarn

before_install:
  - npm install -g node-gyp
  - npm install -g truffle
  - npm install -g yarn

before_script:
  - cd truffle-project

script:
  - npm install
  - yarn gen:loom-key
  - yarn loom:init > /dev/null 2>&1 &
  - yarn loom:run &
  - sleep 5
  - yarn deploy:reset
  - yarn serve > /dev/null 2>&1 &
  # https://create-react-app.dev/docs/running-tests/#travis-ci
  - cd ../web && npm install && npm test
