# Documentation
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

os: linux

sudo: required

language: node_js
node_js:
  - "10"

cache:
  - npm
  - yarn

before_install:
  - npm install -g node-gyp
  - npm install -g truffle
  - npm install -g yarn

before_script:
  - cd truffle-project

script:
  - npm install
  - yarn run:bfa
  - yarn deploy:bfa
  - yarn run:loom
  - yarn deploy:reset:loom
  - cd ../web && npm install && npm test # https://create-react-app.dev/docs/running-tests/#travis-ci
