# Documentation
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

os: linux

language: node_js
node_js:
  - "10"

cache:
  - npm
  - yarn
  - truffle

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g yarn
  - npm install -g node-gyp

before_script:
  - cd truffle-project

script:
  - yarn install
  - yarn gen:loom-key
  - yarn loom:init > /dev/null 2>&1 &
  - yarn loom:run
  - yarn deploy
  - yarn serve > /dev/null 2>&1 &
