# Documentation
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

os: osx

language: node_js
node_js:
  - "10"

cache:
  - npm
  - yarn

before_install:
  - npm install -g yarn

before_script:
  - chmod +x crypto_dragons.sh
  - chmod +x crypto_dragons_functions.sh

script:
  - ./crypto_dragons.sh setup
  - ./crypto_dragons.sh start

  # Run tests here!!

  - ./crypto_dragons.sh stop
