# Documentation
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

os: osx

language: node_js
node_js:
  - "10"

before_install:
  - npm install -g yarn

before_script:
  - chmod +x crypto_dragons.sh
  - chmod +x crypto_dragons_functions.sh

script:
  - ./crypto_dragons.sh setup
  - ./crypto_dragons.sh start 
  - kill -0 $(cat dappchain-scripts/loom.pid)     # Checks if sidechain up & running
  - kill -0 $(cat webclient/webclient.pid)        # Checks if webclient up & running
  - kill -0 $(cat truffle-ethereum/ganache.pid)   # Checks if evm blockchain up & running
