version: '3'

services:
 mongo:
   build: './mongo'
   expose:
     - "27017"
   ports:
     - "27017:27017"

 oracle:
   build:
     context: '.'
     dockerfile: 'oracle/Dockerfile'
   command: "node oracle.js"
   expose:
     - "8081"
     - "46658"
     - "27017"
     - "8545"
   ports:
     - "8081:8081"
     - "46658:46658"
     - "27017:27017"
     - "8545:8545"

 web:
   container_name: web_container
   build:
     context: ./web
     dockerfile: Dockerfile
   image: nicomoccagatta/web_container
   ports:
     - "3000:3000"
   volumes:
     - ./web:/usr/src/app/web
