version: '3'
services:
  loom:
    image: gonzaloguzzardi/cryptodragons:loom_node_v001
    ports:
      - 46656
      - 46658

  bfa:
    image: gonzaloguzzardi/cryptodragons:bfa_node_v004
    ports:
      - 8545
      - 8546
      - 8547
      - 30303

  oracle:
    environment:
      DOCKERENV: 1
    build:
      context: ./oracle
    ports:
      - 8001
      - 8002
      - 8081
    volumes:
      - ./oracle:/usr/src/app/oracle
      - /usr/src/app/oracle/node_modules

  mongo:
    environment:
      DOCKERENV: 1
    build:
      context: ./mongo
    ports:
      - 27017 # process
      - 28017 # http

  sidechain-deploy-and-cli:
    environment:
      DOCKERENV: 1
    build:
      context: ./truffle-project
      dockerfile: DockerfileSidechainSetup
    ports:
      - 8001
    volumes:
      - ./truffle-project:/usr/src/app/side-sv
      - /usr/src/app/side-sv/node_modules

  mainchain-deploy-and-cli:
    environment:
      DOCKERENV: 1
    build:
      context: ./truffle-project
      dockerfile: DockerfileMainchainSetup
    ports:
      - 8002
    volumes:
      - ./truffle-project:/usr/src/app/main-sv
      - /usr/src/app/main-sv/node_modules

  web:
    environment:
      DOCKERENV: 1
    build:
      context: ./web
    ports:
      - 3000
    depends_on:
      - oracle
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules
