version: "3"
services:
  loom:
    image: loomnetwork/loom:1430
    ports:
      - "46656:46656"
      - "46658:46658"

  contract-getter:
    platform: linux/amd64
    environment:
      DOCKERENV: 1
    build:
      context: ./truffle-project
      dockerfile: DockerfileContractGetterSetup
    ports:
      - "8082:8082"
    depends_on:
      - loom
      - bfa
    volumes:
      - ./truffle-project:/usr/src/app/contractGetter
      - /usr/src/app/contractGetter/node_modules

  bfa:
    image: nicomoccagatta/cryptodragons:bfa_node_v010
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
      - "30303:30303"

  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017" # process
      - "28017:28017" # http

  oracle:
    platform: linux/amd64
    environment:
      DOCKERENV: 1
    build:
      context: ./oracle
    ports:
      - 8001
      - 8002
      - "8081:8081"
    depends_on:
      - mongo
      - contract-getter
    volumes:
      - ./oracle:/usr/src/app/oracle
      - /usr/src/app/oracle/node_modules

  web:
    platform: linux/amd64
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - contract-getter
      - oracle
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules
      - /usr/src/app/web/.next
