version: '3'
services:
  # loom:
  #   image: gonzaloguzzardi/cryptodragons:loom_node_v001
  #   ports:
  #     - "46656:46656"
  #     - "46658:46658"

  # sidechain-deploy:
  #   environment:
  #     DOCKERENV: 1
  #   build:
  #     context: ./truffle-project
  #     dockerfile: DockerfileSidechainSetup
  #   ports:
  #     - "8001:8001"
  #     - 46656
  #     - 46658
  #   depends_on:
  #     - loom
  #   volumes:
  #     - ./truffle-project:/usr/src/app/side-sv
  #     - /usr/src/app/side-sv/node_modules

  # bfa:
  #   image: nicomoccagatta/cryptodragons:bfa_node_v010
  #   ports:
  #     - "8545:8545"
  #     - "8546:8546"
  #     - "8547:8547"
  #     - "30303:30303"

  # mainchain-deploy:
  #   environment:
  #     DOCKERENV: 1
  #   build:
  #     context: ./truffle-project
  #     dockerfile: DockerfileMainchainSetup
  #   ports:
  #     - "8002:8002"
  #     - 8545
  #     - 8546
  #     - 8547
  #     - 30303
  #   depends_on:
  #     - bfa
  #   volumes:
  #     - ./truffle-project:/usr/src/app/main-sv
  #     - /usr/src/app/main-sv/node_modules

  # mongo:
  #   build:
  #     context: ./mongo
  #   ports:
  #     - "27017:27017" # process
  #     - "28017:28017" # http

  oracle:
    environment:
      DOCKERENV: 1
    build:
      context: ./oracle
    ports:
      - 8001
      - 8002
      - "8081:8081"
    # depends_on:
      # - sidechain-deploy
      # - mainchain-deploy
      # - mongo
    volumes:
      - ./oracle:/usr/src/app/oracle
      - /usr/src/app/oracle/node_modules

  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - oracle
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules
      - /usr/src/app/web/.next
