version: '3'
services:
  loom:
    image: gonzaloguzzardi/cryptodragons:loom_node_v001
    ports:
      - "46656:46656"
      - "46658:46658"

  # PROBLEMAS PARA CONECTARSE A LA SIDE..
  # sidechain-deploy-and-cli:
  #   build:
  #     context: ./truffle-project
  #     dockerfile: DockerfileSidechainSetup
  #   ports:
  #     - "8001:8001"

  bfa:
    image: gonzaloguzzardi/cryptodragons:bfa_node_v004
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
      - "30303:30303"

  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017" # process
      - "28017:28017" # http

  oracle:
    build:
      context: ./oracle
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8081:8081"

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/app/web
      - '/usr/src/app/web/node_modules'
