FROM ubuntu
WORKDIR /usr/bfa

RUN apt-get update
RUN apt-get install -y software-properties-common

COPY . .

RUN cd /usr/bfa
COPY init_docker.sh .
RUN chmod +x ./init_docker.sh
RUN ./init_docker.sh
RUN geth --datadir devnet/network/node init devnet/devnet.json
RUN geth --datadir devnet/network/node/ --syncmode 'full' --port 30303 --rpc --rpcaddr 'localhost' --rpcport 8545 --rpcapi 'personal,db,eth,net,web3,txpool,miner' --networkid 12345 --gasprice '1' --unlock '0x28863498efede12296888f7ca6cf0b94974fbdbc' --password /dev/null --mine
RUN geth attach http://localhost:8545
EXPOSE 8545 8546 8547 30303 30303/udp
ENTRYPOINT ["geth"]

# CMD ["geth", "--datadir", "network/node", "--syncmode", "full", "--port", "30303 ", "--rpc", "--rpcaddr", "'localhost", "--rpcport", "8545", "--rpcapi", "'personal,db,eth,net,web3,txpool,miner'", "--networkid", "12345", "--gasprice", "'1'", "--unlock", "0xb5b1f1e6dfd631a87569acb8b524bb5f2dc27983", "--password", "/dev/null", "--mine"]